### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by neilboyd** [neilboyd/tapiriik#1]
- [x] Run in Docker locally - #4 
- [x] GitHub Action to deploy to Docker Hub. - #8
- [x] Run it in Azure - #10 (can only run single instance until I fix #9)
